<a href="https://colab.research.google.com/github/Annepikson/HypatiaAcademy/blob/master/Untitled7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

file="https://raw.githubusercontent.com/InterImm/dataset-planets-in-solar-system/master/dataset/planets_in_solar_system.csv"
df = pd.read_csv(file)
df

,name,equatorial_diameter,mass,semi_major_axis,orbital_period,inclination_to_suns_equator,orbital_eccentricity,rotation_period,confirmed_moons,axial_tilt,rings,atmosphere
0,Mercury,0.382,0.06,0.39,0.24,3.38,0.206,58.64,0,0.04,no,minimal
1,Venus,0.949,0.82,0.72,0.62,3.86,0.007,−243.02,0,177.36,no,"CO2, N2"
2,Earth,1.000,1.00,1.00,1.00,7.25,0.017,1,1,23.44,no,"N2, O2, Ar"
3,Mars,0.532,0.11,1.52,1.88,5.65,0.093,1.03,2,25.19,no,"CO2, N2, Ar"
4,Jupiter,11.209,317.80,5.20,11.86,6.09,0.048,0.41,79,3.13,yes,"H2, He"
5,Saturn,9.449,95.20,9.54,29.46,5.51,0.054,0.43,82,26.73,yes,"H2, He"
6,Uranus,4.007,14.60,19.22,84.01,6.48,0.047,−0.72,27,97.77,yes,"H2, He, CH4"
7,Neptune,3.883,17.20,30.06,164.80,6.43,0.009,0.67,14,28.32,yes,"H2, He, CH4"

In [6]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [5]:
df.columns

Index(['name', 'equatorial_diameter', 'mass', 'semi_major_axis',
       'orbital_period', 'inclination_to_suns_equator', 'orbital_eccentricity',
       'rotation_period', 'confirmed_moons', 'axial_tilt', 'rings',
       'atmosphere'],
      dtype='object')