#### Paphos Weather

This page shows various metrics for the weather in Paphos, Cyprus.

Weather data is purchased from Openweather Marketplace [here](https://home.openweathermap.org/marketplace/my_orders)

Download this weather data from here https://drive.google.com/file/d/1swgJS4r9f0CqTd0ZXAOnmJmmmKdNJUUA/view?usp=sharing

In [142]:
def calculate_heat_index(temperature, relative_humidity):
    heat_index = (-8.784695 +
                  1.61139411 * temperature +
                  (2.338549 * relative_humidity) +
                  (-0.14611605 * temperature * relative_humidity) +
                  (-0.01230809 * (temperature ** 2)) +
                  (-0.01642482 * (relative_humidity ** 2)) +
                  (0.00221173 * (temperature ** 2) * relative_humidity) +
                  (0.00072546 * temperature * (relative_humidity ** 2)) +
                  (-0.000003582 * (temperature ** 2) * (relative_humidity ** 2)))
    return heat_index

In [1]:

from datetime import date
from datetime import datetime
import time
import pandas as pd

def toDate(epoch_time):
    return datetime.fromtimestamp(epoch_time)

In [2]:
import pandas as pd

df=pd.read_json('/Users/walkerrowe/Documents/hypatia/pathosWeather.json')

In [3]:
df.columns

Index(['city_name', 'lat', 'lon', 'main', 'wind', 'clouds', 'weather', 'dt',
       'dt_iso', 'timezone', 'rain'],
      dtype='object')

In [4]:
df['dt'].map(toDate)

0        2000-01-01 02:00:00
1        2000-01-01 03:00:00
2        2000-01-01 04:00:00
3        2000-01-01 05:00:00
4        2000-01-01 06:00:00
                 ...
181459   2020-09-12 22:00:00
181460   2020-09-12 23:00:00
181461   2020-09-13 00:00:00
181462   2020-09-13 01:00:00
181463   2020-09-13 02:00:00
Name: dt, Length: 181464, dtype: datetime64[ns]

We have to convert the epoch time to ISO Date, which is something we can read.

The map function runs a function over a series.  A series means a dataframe with one column.  When we write df['new column'] = df['some column'].map(somefunction) it adds the new columns to the dataframe.

In [5]:
df['dateTime']=df['dt'].map(lambda l: toDate(l).strftime("%Y-%m-%d %H:%M:%S"))

In [89]:
df['month']=df['dt'].map(lambda l: toDate(l).strftime("%m"))
df['day']=df['dt'].map(lambda l: toDate(l).strftime("%d"))
df['year']=df['dt'].map(lambda l: toDate(l).strftime("%y"))
df['hour']=df['dt'].map(lambda l: toDate(l).strftime("%H"))
df['hour']=pd.to_numeric(df['hour'])

In [140]:
df['temp']=df["main"].map(lambda x: (x["temp"]-32)*(5/9))
df['temp_min']=df["main"].map(lambda x: (x["temp_min"]-32)*(5/9))
df['temp_max']=df["main"].map(lambda x: (x["temp_max"]-32)*(5/9))
df['humidity']=df["main"].map(lambda x: x["humidity"])

In [146]:
df['heatIndex'] = df.apply(lambda row: calculate_heat_index(row['temp'], row['humidity']), axis=1)

In [148]:

summer=df.loc[df['month'].isin(['06','07','08'])]
afternoon=df.loc[(df['hour'] > 13)]

In [153]:
hot=afternoon[['year','month','day', 'hour' ,'temp','temp_min','temp_max','hour', 'humidity', 'heatIndex']]

We want to caculate the average temperature by date usign the mean() function.  But the problem is that the date is an object inside the **main** object.  See below how to fix that.

In [154]:
hot.sort_values(by='temp',ascending=False).head(50)

,year,month,day,hour,temp,temp_min,temp_max,hour,humidity,heatIndex
178644,20,05,18,15,35.777778,27.561111,40.000000,15,30,35.822245
181259,20,09,04,14,35.127778,30.650000,38.450000,14,79,56.449251
178645,20,05,18,16,35.088889,27.561111,38.061111,16,28,34.395851
178643,20,05,18,14,35.050000,27.561111,38.888889,14,36,36.173117
181260,20,09,04,15,34.972222,30.650000,38.450000,15,70,50.238187
178646,20,05,18,17,34.627778,29.044444,37.222222,17,28,33.772205
109907,12,07,15,14,34.538889,28.544444,37.600000,14,36,35.328413
178595,20,05,16,14,34.488889,26.683333,37.222222,14,36,35.247538
181261,20,09,04,16,34.488889,30.650000,38.450000,16,70,48.489502
109908,12,07,15,15,34.477778,28.511111,36.600000,15,36,35.229608
153395,17,07,01,14,34.400000,27.727778,37.000000,14,50,39.284367
181403,20,09,10,14,34.400000,29.944444,35.844444,14,36,35.104532
109909,12,07,15,16,34.277778,28.516667,35.500000,16,39,35.648248
109910,12,07,15,17,34.238889,28.605556,36.000000,17,41,36.113172
153419,17,07,02,14,34.177778,27.766667,38.000000,14,49,38.442946
178667,20,05,19,14,34.172222,25.688889,38.888889,14,52,39.482801
153396,17,07,01,15,34.150000,27.461111,38.600000,15,53,39.797161
181235,20,09,03,14,34.127778,28.855556,39.000000,14,62,43.402958
153421,17,07,02,16,34.100000,27.722222,37.200000,16,56,40.818122
181405,20,09,10,16,34.088889,29.944444,35.844444,16,46,37.286548
178619,20,05,17,14,34.038889,27.405556,37.777778,14,38,34.998400
181404,20,09,10,15,34.038889,29.944444,35.844444,15,46,37.186472
178669,20,05,19,16,34.027778,25.688889,38.888889,16,55,40.250734
136644,15,08,03,15,33.977778,29.172222,35.900000,15,67,45.241315
153397,17,07,01,16,33.961111,27.194444,38.100000,16,56,40.466520
153420,17,07,02,15,33.938889,27.805556,37.100000,15,66,44.647812
136645,15,08,03,16,33.900000,29.377778,36.200000,16,75,49.010167
22283,02,07,17,14,33.861111,28.366667,37.000000,14,52,38.766250
181163,20,08,31,14,33.850000,28.672222,37.000000,14,70,46.267616
92751,10,07,31,18,33.827778,28.527778,35.800000,18,44,36.192010
181379,20,09,09,14,33.800000,28.877778,36.111111,14,55,39.692526
153422,17,07,02,17,33.788889,29.494444,35.000000,17,47,36.990615
181380,20,09,09,15,33.750000,28.877778,36.111111,15,55,39.571361
153423,17,07,02,18,33.688889,29.550000,35.000000,18,50,37.719088
22571,02,07,29,14,33.688889,28.583333,36.750000,14,56,39.788608
65655,07,06,28,18,33.661111,27.244444,36.200000,18,26,32.251957
181381,20,09,09,16,33.661111,28.877778,35.561111,16,55,39.357172
65654,07,06,28,17,33.638889,27.283333,36.000000,17,30,32.809444
22284,02,07,17,15,33.600000,28.511111,36.900000,15,57,39.937930
65653,07,06,28,16,33.572222,27.038889,35.027778,16,34,33.423424
4500,00,07,06,15,33.561111,27.611111,36.400000,15,46,36.250829
22575,02,07,29,18,33.538889,28.966667,35.500000,18,59,40.536582
180419,20,07,31,14,33.511111,28.150000,36.350000,14,66,43.325473
178647,20,05,18,18,33.500000,29.044444,35.644444,18,20,31.443036
22573,02,07,29,16,33.500000,28.705556,37.127778,16,63,42.021257
181139,20,08,30,14,33.461111,29.761111,35.961111,14,55,38.880939
178620,20,05,17,15,33.438889,27.405556,38.327778,15,45,35.743430
178668,20,05,19,15,33.427778,25.688889,38.327778,15,55,38.802332
22572,02,07,29,15,33.422222,28.683333,37.061111,15,62,41.397563
181406,20,09,10,17,33.411111,29.344444,34.000000,17,56,39.112186